# Generated by Django 5.2.17 on 2026-09-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('news', 'Latest News'), ('publication', 'Publications'), ('event', 'Events'), ('career', 'Career Opportunities'), ('startup', 'Startup Competitions'), ('conference', 'International Conferences')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, help_text='Path under static/, e.g. images/insights/example.jpg', max_length=255)),
                ('published_at', models.DateField()),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(blank=True, help_text='Path under static/, e.g. images/partners/example.svg', max_length=255)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('date_range', models.CharField(blank=True, help_text='e.g. "2025 – Ongoing"', max_length=100)),
                ('summary', models.TextField()),
                ('image', models.CharField(blank=True, help_text='Path under static/, e.g. images/projects/example.jpg', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Projects", "Partners"', max_length=100)),
                ('value', models.CharField(help_text='e.g. "20+", "3,000+"', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
